/// @description ...
/// @param {Type} name: ...
/// @returns {Type}
function ObjectShaderEvent(){
    // TODO: this will hold an object shader event which is similar to the draw event shader...
    // will accept 
}